//
// Created by mctrivia on 31/03/24.
//
// ============================================================
// WARNING: THIS FILE HAS AN UPSTREAM TEST DEPENDENCY
// ============================================================
// All tests in this suite require testFiles/rpcTest.db, which
// is generated by:
//
//   DigiAssetTransaction.existingAssetTransactions
//   (tests/DigiAssetTransactionTest.cpp)
//
// That test requires a live IPFS node and DigiByte Core node.
// If rpcTest.db is missing, every test in this suite will FAIL
// with a clear error rather than silently skip.
//
// Do NOT replace the FAIL() in SetUp() with GTEST_SKIP() —
// silent skipping masks missing coverage.
// ============================================================
#include "RPCMethods.h"
#include "AppMain.h"
#include "utils.h"

AppMain* RPCMethodsTest::appMain = nullptr;
DigiByteCore* RPCMethodsTest::dgb = nullptr;
Database* RPCMethodsTest::db = nullptr;
IPFS* RPCMethodsTest::ipfs = nullptr;
PermanentStoragePoolList* RPCMethodsTest::psp = nullptr;
ChainAnalyzer* RPCMethodsTest::analyzer = nullptr;
RPC::Cache* RPCMethodsTest::rpcCache = nullptr;

void RPCMethodsTest::SetUpTestSuite() {

    if (!utils::fileExists("../tests/testFiles/rpcTest.db")) {
        std::cerr << "\n[  FAILED  ] rpcTest.db not found\n"
                  << "             Run DigiAssetTransaction.existingAssetTransactions first (requires IPFS)\n\n";
        return; // db stays null; SetUp() will fail each test with the above reason
    }

    appMain = AppMain::GetInstance();
    dgb = new DigiByteCore();
    dgb->setFileName("config.cfg");
    dgb->makeConnection();
    appMain->setDigiByteCore(dgb);

    db = new Database("../tests/testFiles/rpcTest.db");
    appMain->setDatabase(db);

    ipfs = new IPFS("config.cfg", false);
    appMain->setIPFS(ipfs);
    ipfs->start();

    psp = new PermanentStoragePoolList("config.cfg");
    appMain->setPermanentStoragePoolList(psp);

    analyzer = new ChainAnalyzer();
    analyzer->loadFake(17579454, -1);
    ///do not start() analyzer we are using in fake mode
    appMain->setChainAnalyzer(analyzer);

    rpcCache = new RPC::Cache();
    appMain->setRpcCache(rpcCache);
}

void RPCMethodsTest::TearDownTestSuite() {
    //everything may still be null if SetUpTestSuite bailed out(missing rpcTest.db or a
    //throwing constructor) - an unguarded ipfs->stop() here segfaulted the whole run
    if (ipfs != nullptr) ipfs->stop(); // stop IPFS thread before deleting anything
    if (appMain != nullptr) appMain->reset(); // clear AppMain pointers before objects are deleted
    delete dgb;
    dgb = nullptr;
    delete ipfs;
    ipfs = nullptr;
    delete psp;
    psp = nullptr;
    delete db;
    db = nullptr;
    delete analyzer;
    analyzer = nullptr;
    delete rpcCache;
    rpcCache = nullptr;

    remove("../tests/testFiles/rpcTest.db");
    remove("../tests/testFiles/rpcTest.db-wal");
    remove("../tests/testFiles/rpcTest.db-shm");
}
