///This file is automatically generated by CMakeLists.txt do not edit

#include "RPC/MethodList.h"

namespace RPC {
    std::map<std::string, std::function<Response(const Json::Value&)>> methods = {
        {"addressstats", Methods::addressstats},
        {"algostats", Methods::algostats},
        {"asyncclear", Methods::asyncclear},
        {"asyncget", Methods::asyncget},
        {"asyncstart", Methods::asyncstart},
        {"debugwaittimes", Methods::debugwaittimes},
        {"getaddressholdings", Methods::getaddressholdings},
        {"getaddresskyc", Methods::getaddresskyc},
        {"getassetdata", Methods::getassetdata},
        {"getassetholders", Methods::getassetholders},
        {"getassetindexes", Methods::getassetindexes},
        {"getdgbequivalent", Methods::getdgbequivalent},
        {"getdomainaddress", Methods::getdomainaddress},
        {"getexchangerates", Methods::getexchangerates},
        {"getipfscount", Methods::getipfscount},
        {"getoldstreamkey", Methods::getoldstreamkey},
        {"getpsp", Methods::getpsp},
        {"getrandom", Methods::getrandom},
        {"getrawtransaction", Methods::getrawtransaction},
        {"gettxout", Methods::gettxout},
        {"listaddresshistory", Methods::listaddresshistory},
        {"listassetissuances", Methods::listassetissuances},
        {"listassets", Methods::listassets},
        {"listlastassets", Methods::listlastassets},
        {"listlastassetspageindexes", Methods::listlastassetspageindexes},
        {"listlastblocks", Methods::listlastblocks},
        {"listunspent", Methods::listunspent},
        {"resyncmetadata", Methods::resyncmetadata},
        {"send", Methods::send},
        {"sendmany", Methods::sendmany},
        {"sendtoaddress", Methods::sendtoaddress},
        {"shutdown", Methods::shutdown},
        {"syncstate", Methods::syncstate},
        {"version", Methods::version},
    };
}